name: project-lint

on: push
jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: "16.9.0"
    #
    - name: npm install
      run: |
        make install
    #
    - name: Run linter
      run: |
        make lint
