name: project-lint

on: push
jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16.9.0"
      #
      - name: npm install
        run: |
          make install
      #
      - name: Run linter
        run: |
          make lint
      - name: Run tests
       run: |
         make test
      - name: Test & publish code coverage
      Publish code coverage on Code Climate
      https://github.com/paambaati/codeclimate-action
       uses: paambaati/codeclimate-action@v2.7.5
      Add Code Climate secret key
       env:
         CC_TEST_REPORTER_ID: ${{ secrets.CODECOVERAGE_ID }}
       with:
         coverageCommand: make test-coverage
         debug: true
